### ISSUE TITLE
如何使用他呢？并没找到我应该如何输入输出

### ISSUE THREAD

**Issue by sunbinghonter** [DeepSoftwareAnalytics/SoTaNa#2]

**Comment by s1530129650** [comment]
```
cd webui
bash run_generation_param.sh  $model_size $data_size
```
for example,
execute the following command,
```
bash run_generation_param.sh 7 1000
```
you will obtain,

![image](https://github.com/DeepSoftwareAnalytics/SoTaNa/assets/34572118/2c2c5dfa-7cdf-4dd2-b3fe-6d4287c3d70c)
