### ISSUE TITLE
Hugging face repo?

### ISSUE THREAD

**Issue by yhyu13** [DeepSoftwareAnalytics/SoTaNa#3]
Hi,

Would you like to point out the hugging face repo for model release in the readme?

**Comment by s1530129650** [comment]
|Model|Checkpoint|
  | ----- |------| 
  |Enoch/SoTana-7B-lora-100000|🤗 <a href="https://huggingface.co/Enoch/SoTana-7B-lora-100000" target="_blank">HF Link</a>|
  |Enoch/SoTana-13B-lora-100000|🤗 <a href="https://huggingface.co/Enoch/SoTana-13B-lora-100000" target="_blank">HF Link</a>|
  |Enoch/SoTana-30B-lora-100000|🤗 <a href="https://huggingface.co/Enoch/SoTana-30B-lora-100000" target="_blank">HF Link</a>|



added. Thanks!
